### ISSUE TITLE
One directional dangling edge breaks contraction (with test case)

### ISSUE THREAD

**Issue by mkv123** [royhobbstn/contraction-hierarchy-js#1]
First of all, thanks for writing a great self contained contraction hierarchy library.  However in trying to use it I ran into an issue where contraction would fail. 

Below is my minimal test case (jest) and the error I get.
 
```
import { Graph } from 'contraction-hierarchy-js';

describe("Test contraction", ()=>{

    test("Check output", () => {
        const g = new Graph();
        g.addEdge("n:24", "n:76", {"_id": 44, "_cost": 0.002}, null, false);
        g.addEdge("n:76", "n:24", {"_id": 45, "_cost": 0.002}, null, false);
        g.addEdge("n:76", "n:67", {"_id": 210, "_cost": 0.01}, null, false);
        g.contractGraph()
    });
});
```

Following error:
```
       TypeError: Cannot read property 'filter' of undefined

       8 |         g.addEdge("n:76", "n:24", {"_id": 45, "_cost": 0.002}, null, false);
       9 |         g.addEdge("n:76", "n:67", {"_id": 210, "_cost": 0.01}, null, false);
    > 10 |         g.contractGraph()
         |           ^
      11 |     });
      12 | });

      at Object.runDijkstra (node_modules/contraction-hierarchy-js/src/contract.js:375:10)
      at node_modules/contraction-hierarchy-js/src/contract.js:285:25
          at Array.forEach (<anonymous>)
      at Graph._contract (node_modules/contraction-hierarchy-js/src/contract.js:254:20)
      at getVertexScore (node_modules/contraction-hierarchy-js/src/contract.js:20:33)
      at node_modules/contraction-hierarchy-js/src/contract.js:45:19
          at Array.forEach (<anonymous>)
      at Graph.contractGraph (node_modules/contraction-hierarchy-js/src/contract.js:43:40)
```

**Comment by royhobbstn** [comment]
Thanks for such a good test case.  I suspect the issue is because the nodes are not real world coordinates ("n:76" vs "126.5,76.8", but I'm not certain since its been a while since I built this).
If that's the case, I'll update the documentation (because that constraint really should have been mentioned).  I can also see if there is a workaround for non-coordinate data, though that may take a bit longer.  I'll try to come up with some answers ASAP.  Are you under any time constraints currently?

**Comment by mkv123** [comment]
As I am not routing simple real world coordinates and really appreciated the manual edge insertion api where you can set your own costs, a limitation to have to use wgs84 coordinates would be a deal breaker for me. However looking at the code it doesn't look like it is treating the node ids as coordinates, so hopefully that isn't a case.

This is currently blocking my progress, so I am investigating further. However as I only understand  contraction hierarchies on a very high level, your help would be very much appreciated.

Looks like the adjacency_list only gets two nodes instead of the three the data has, so when current.id is the index 2 it breaks.

**Comment by mkv123** [comment]
Ok, so I think the problem is that when the adjacency_list is populated, it only has the  the start nodes as "keys", which makes sense, it populates "from this node, you can get to these nodes". As the edge 210 is one directional, its endpoint n:67 doesn't get added to the adjacency list.

However then in the contraction phase, the code adds the end nodes to the openset. As it pops the next current from the open set that is n:67 (or actually index 2), it has no entry in the adjacency list and things break.

So two ways to fix: Add also end points to adjacency list, just make the list empty initially and then add to them. I suppose this would waste some memory.

Alternatively, fix the contraction to not expect all nodes to be in the adjacency list, as you may not get anywhere from some nodes.

So at https://github.com/royhobbstn/contraction-hierarchy-js/blob/master/src/contract.js#L374

something like (adjacency_list[current.id] || [] ).filter ...  would fix this test case.

**Comment by mkv123** [comment]
I hacked my local copy to confirm and now this test case passes

```Javascript
describe("Test contraction", ()=>{
    test("Check", () => {
        const g = new Graph();
        g.addEdge("n:24", "n:76", {"_id": 44, "_cost": 0.002}, null, false);
        g.addEdge("n:76", "n:24", {"_id": 45, "_cost": 0.002}, null, false);
        g.addEdge("n:76", "n:67", {"_id": 210, "_cost": 0.01}, null, false);
        g.contractGraph()
        const p = g.createPathfinder({ ids: true, path: false, nodes: true, properties: false })
        const result = p.queryContractionHierarchy("n:24", "n:67");
        expect(result.ids).toEqual([44,210]);
        expect(result.nodes).toEqual(["n:24", "n:76", "n:67"]);
    });
});
```

**Comment by royhobbstn** [comment]
Nice work!  I'll update the library and republish at some point today.  Let me know if you run into any more issues.  The library hasn't really been put through a lot of tests (especially on networks that aren't geographic, and aren't bidirectional), so I'm a bit nervous about what you might find.

**Comment by royhobbstn** [comment]
v1.2.1 published.

**Comment by mkv123** [comment]
@royhobbstn Excellent, thanks for the quick turnaround on the release.
